// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAyQhzJp_B4WB2Jh0RP0trpfRzWmROBvyA',
    appId: '1:873377705460:web:5784e7c6fac9ecb23c5da1',
    messagingSenderId: '873377705460',
    projectId: 'couple-todo-a5771',
    authDomain: 'couple-todo-a5771.firebaseapp.com',
    storageBucket: 'couple-todo-a5771.appspot.com',
    measurementId: 'G-D8NKCM90YY',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCYW-hRDXMi3amL9cd-k0IEtVfXu-jVETo',
    appId: '1:873377705460:android:4a12acb2ad169e723c5da1',
    messagingSenderId: '873377705460',
    projectId: 'couple-todo-a5771',
    storageBucket: 'couple-todo-a5771.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAW7kpUEncshyZKWqAK6EIXVeMTnGzLVKo',
    appId: '1:873377705460:ios:8932ccfd77c46ede3c5da1',
    messagingSenderId: '873377705460',
    projectId: 'couple-todo-a5771',
    storageBucket: 'couple-todo-a5771.appspot.com',
    iosClientId: '873377705460-a68kohinr2s6050fufu2c7e92jqkn11c.apps.googleusercontent.com',
    iosBundleId: 'com.example.dodo',
  );
}
